#
#      ░█████╗░██████╗░██████╗░░█████╗░░██╗░░░░░░░██╗███████╗███████╗███████╗███████╗░█████╗░████████╗░██████╗
#      ██╔══██╗██╔══██╗██╔══██╗██╔══██╗░██║░░██╗░░██║██╔════╝██╔════╝██╔════╝██╔════╝██╔══██╗╚══██╔══╝██╔════╝
#      ███████║██████╔╝██████╔╝██║░░██║░╚██╗████╗██╔╝█████╗░░█████╗░░█████╗░░█████╗░░██║░░╚═╝░░░██║░░░╚█████╗░
#      ██╔══██║██╔══██╗██╔══██╗██║░░██║░░████╔═████║░██╔══╝░░██╔══╝░░██╔══╝░░██╔══╝░░██║░░██╗░░░██║░░░░╚═══██╗
#      ██║░░██║██║░░██║██║░░██║╚█████╔╝░░╚██╔╝░╚██╔╝░███████╗██║░░░░░██║░░░░░███████╗╚█████╔╝░░░██║░░░██████╔╝
#      ╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚═╝░░╚══════╝╚═╝░░░░░╚═╝░░░░░╚══════╝░╚════╝░░░░╚═╝░░░╚═════╝░
#

particles-spawn-delay: 0.5 # In seconds

# EXPLOSION_NORMAL, CRIT, HEART, TOTEM, SMOKE_NORMAL, CLOUD (Default: CLOUD)
particle-type: 'CLOUD'

particles-count: 1

#
#      ██████╗░██╗░░░██╗  ██╗░░░░░███████╗██████╗░███████╗██╗░░░██╗░░░██████╗░██╗░░░██╗
#      ██╔══██╗╚██╗░██╔╝  ██║░░░░░██╔════╝██╔══██╗██╔════╝██║░░░██║░░░██╔══██╗██║░░░██║
#      ██████╦╝░╚████╔╝░  ██║░░░░░█████╗░░██║░░██║█████╗░░╚██╗░██╔╝░░░██████╔╝██║░░░██║
#      ██╔══██╗░░╚██╔╝░░  ██║░░░░░██╔══╝░░██║░░██║██╔══╝░░░╚████╔╝░░░░██╔══██╗██║░░░██║
#      ██████╦╝░░░██║░░░  ███████╗███████╗██████╔╝███████╗░░╚██╔╝░░██╗██║░░██║╚██████╔╝
#      ╚═════╝░░░░╚═╝░░░  ╚══════╝╚══════╝╚═════╝░╚══════╝░░░╚═╝░░░╚═╝╚═╝░░╚═╝░╚═════╝░
#